matrix:
  include:
    - os: osx
      osx_image: xcode9.3
      language: node_js
      node_js: "10"
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

    - os: linux
      services: docker
      language: generic

cache:
  directories:
  - node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder

before_install:
  - |
    if [ $TRAVIS_OS_NAME == osx ]; then
      mkdir -p /tmp/git-lfs && curl -L https://github.com/github/git-lfs/releases/download/v2.3.1/git-lfs-darwin-amd64-2.3.1.tar.gz | tar -xz -C /tmp/git-lfs --strip-components 1
      export PATH="/tmp/git-lfs:$PATH"
    fi
install:
  - npm install

before_script:
  - git lfs pull

script:
  - npm run dist-mac
  - npm run dist-linux
before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

deploy:
  provider: releases
  api_key:
    secure: ${GITHUB_TOKEN}
  file_glob: true
  file:
    - "release/**.zip"
    - "release/**.dmg"
    - "release/**.exe"
    - "release/**.yml"
  skip_cleanup: true
  on:
    repo: ucdbook/electron-app
    tags: true
  draft: false
branches:
  only:
    - /^v\d+(\.\d+)+$/
